---  
# TO RUN THIS PLAYBOOK, LOGIN WITH ROOT ACCOUNT IN HOST MACHINE AND RUN THE PLAYBOOK
# Ex: ansible-playbook k8s-master-setup.yml -vvv -e "password=kubernetes" --ask-pass
#- name: create user with sudo access
#  hosts: 
#  - 10.106.179.71
#  - 10.106.179.72
#  - 10.106.179.73
#
#  remote_user: root
#  
#  vars: 
#    username: 
#      - { name: "kubeuser", state: present, sudo: "yes" }
#    groupname: 
#      - { name: "admin" , state: present }
#    # Pass "password" from command line as mentioned above 
#
#  roles:
#  - manage_user

- name: Kubernetes setup on Master
  hosts: 10.106.175.163
  remote_user: root
    #remote_user: kubemaster
    #become: yes

  vars:
    kubernetes_allow_pods_on_master: false
    kubernetes_pod_network:
      cni: 'calico' 
      cidr: '192.168.0.0/16'
    kubernetes_role: 'master'
    kubernetes_version: '1.23.4'
    kubernetes_version_rhel_package: '1.23.4'

  roles:
    - { role: ansible-role-swap, swap_file_state: absent }
    - ansible-role-docker
    - ansible-role-kubernetes

- name: Kubernetes setup on Workers
  hosts: 
  - 10.106.175.164
  - 10.106.175.165
  remote_user: root

  vars:
    kubernetes_role: "node"
    kubernetes_version: '1.23.4'
    kubernetes_version_rhel_package: '1.23.4'

  roles:
    - { role: ansible-role-swap, swap_file_state: absent }
    - ansible-role-docker
    - ansible-role-kubernetes
